package com.edgedo.sys.entity.article;



import java.util.Date;

/**
 * 文章实体
 */
public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.small_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String smallImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.big_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String bigImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.insert_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String insertImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_time
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.remark1
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.remark2
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    private String content;
    
    private Integer state;//状态 1禁用 2启用
    
    
    private Integer pageIndex;
    
    private Integer pageSize;

    private String imgBase64Str1;//小图

    private String imgBase64Str2;//大图

    private String imgBase64Str3;//插图

    private String articleAddress;//文章出处

    private String videoAuthor;//录音者

    public String getArticleAddress() {
        return articleAddress;
    }

    public Article setArticleAddress(String articleAddress) {
        this.articleAddress = articleAddress;
        return this;
    }

    public String getVideoAuthor() {
        return videoAuthor;
    }

    public Article setVideoAuthor(String videoAuthor) {
        this.videoAuthor = videoAuthor;
        return this;
    }

    public String getImgBase64Str1() {
        return imgBase64Str1;
    }

    public Article setImgBase64Str1(String imgBase64Str1) {
        this.imgBase64Str1 = imgBase64Str1;
        return this;
    }

    public String getImgBase64Str2() {
        return imgBase64Str2;
    }

    public Article setImgBase64Str2(String imgBase64Str2) {
        this.imgBase64Str2 = imgBase64Str2;
        return this;
    }

    public String getImgBase64Str3() {
        return imgBase64Str3;
    }

    public Article setImgBase64Str3(String imgBase64Str3) {
        this.imgBase64Str3 = imgBase64Str3;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    
    
    public Integer getId() {
        return id;
    }

    public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.small_imgurl
     *
     * @return the value of article.small_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    
    
    public String getSmallImgurl() {
        return smallImgurl;
    }

    public Integer getPageIndex() {
		return pageIndex;
	}

	public void setPageIndex(Integer pageIndex) {
		this.pageIndex = pageIndex;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.small_imgurl
     *
     * @param smallImgurl the value for article.small_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setSmallImgurl(String smallImgurl) {
        this.smallImgurl = smallImgurl == null ? null : smallImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.big_imgurl
     *
     * @return the value of article.big_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getBigImgurl() {
        return bigImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.big_imgurl
     *
     * @param bigImgurl the value for article.big_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setBigImgurl(String bigImgurl) {
        this.bigImgurl = bigImgurl == null ? null : bigImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.insert_imgurl
     *
     * @return the value of article.insert_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getInsertImgurl() {
        return insertImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.insert_imgurl
     *
     * @param insertImgurl the value for article.insert_imgurl
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setInsertImgurl(String insertImgurl) {
        this.insertImgurl = insertImgurl == null ? null : insertImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.remark1
     *
     * @return the value of article.remark1
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.remark1
     *
     * @param remark1 the value for article.remark1
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.remark2
     *
     * @return the value of article.remark2
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.remark2
     *
     * @param remark2 the value for article.remark2
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Thu Aug 22 15:20:55 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}